package com.csr.datasearching.model;

public class Station {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.id
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.name
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.lat
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    private Float lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.lng
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    private Float lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.address
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.porvince
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    private String porvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.city
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.area
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.street_id
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    private String streetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.detail
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.uid
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    private String uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.id
     *
     * @return the value of station.id
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.id
     *
     * @param id the value for station.id
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.name
     *
     * @return the value of station.name
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.name
     *
     * @param name the value for station.name
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.lat
     *
     * @return the value of station.lat
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.lat
     *
     * @param lat the value for station.lat
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.lng
     *
     * @return the value of station.lng
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public Float getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.lng
     *
     * @param lng the value for station.lng
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public void setLng(Float lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.address
     *
     * @return the value of station.address
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.address
     *
     * @param address the value for station.address
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.porvince
     *
     * @return the value of station.porvince
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public String getPorvince() {
        return porvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.porvince
     *
     * @param porvince the value for station.porvince
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public void setPorvince(String porvince) {
        this.porvince = porvince == null ? null : porvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.city
     *
     * @return the value of station.city
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.city
     *
     * @param city the value for station.city
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.area
     *
     * @return the value of station.area
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.area
     *
     * @param area the value for station.area
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.street_id
     *
     * @return the value of station.street_id
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public String getStreetId() {
        return streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.street_id
     *
     * @param streetId the value for station.street_id
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public void setStreetId(String streetId) {
        this.streetId = streetId == null ? null : streetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.detail
     *
     * @return the value of station.detail
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.detail
     *
     * @param detail the value for station.detail
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.uid
     *
     * @return the value of station.uid
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.uid
     *
     * @param uid the value for station.uid
     *
     * @mbg.generated Fri Oct 15 15:19:44 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }
}